# Generated by Django 3.0.4 on 2020-09-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.CharField(max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('date_seen', models.DateTimeField(blank=True, null=True, verbose_name='Seen date')),
                ('seen', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('interests', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('university', models.CharField(max_length=254)),
                ('email_body', models.TextField),
                ('reminder_mail', models.TextField),
            ],
        ),
    ]
